# .travis.yml
language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c "tests/phpunit.xml"  tests

after_script:
  - php vendor/bin/coveralls
